clear;clc;
interval = 3;
cm=lines(20);
hold off;

load('BAchangeB');
plot(Bs,fValUBs,Bs,fValFKs,Bs,fValLKs,Bs,fValLBs);
legend('Knapsack Upper Bound','FK-Greedy','LK-Greedy','Knapsack Lower Bound','Location','southeast');
xlabel('Budget');
ylabel('Solution value');
title('PAP on BA networks, |V|=1000, 30 replications');
hold on; 
numBs = length(Bs);
rge = 1:interval:numBs;
CIUBs = varUBs*1.96/sqrt(numBs);
CIFKs = varFKs*1.96/sqrt(numBs);
CILKs = varLKs*1.96/sqrt(numBs);
CILBs = varLBs*1.96/sqrt(numBs);
errorbar(Bs(rge),fValUBs(rge),CIUBs(rge),'o','markersize',1,'color',cm(1,:));
errorbar(Bs(rge),fValFKs(rge),CIFKs(rge),'o','markersize',1,'color',cm(2,:));
errorbar(Bs(rge),fValLKs(rge),CILKs(rge),'o','markersize',1,'color',cm(3,:));
errorbar(Bs(rge),fValLBs(rge),CILBs(rge),'o','markersize',1,'color',cm(4,:));
xlim([Bs(1),Bs(end)]);

figure();
load('BAchangeN');
plot(Ns,fValUBs,Ns,fValFKs,Ns,fValLKs,Ns,fValLBs);
legend('Knapsack Upper Bound','FK-Greedy','LK-Greedy','Knapsack Lower Bound','Location','southeast');
xlabel('Number of Nodes');
ylabel('Solution value');
title('PAP on BA networks, B=3000, 30 replications');
hold on; 
numBs = length(Ns);
rge = 1:interval:numBs;
CIUBs = varUBs*1.96/sqrt(numNs);
CIFKs = varFKs*1.96/sqrt(numNs);
CILKs = varLKs*1.96/sqrt(numNs);
CILBs = varLBs*1.96/sqrt(numNs);
cm=lines(20);
errorbar(Ns(rge),fValUBs(rge),CIUBs(rge),'o','markersize',1,'color',cm(1,:));
errorbar(Ns(rge),fValFKs(rge),CIFKs(rge),'o','markersize',1,'color',cm(2,:));
errorbar(Ns(rge),fValLKs(rge),CILKs(rge),'o','markersize',1,'color',cm(3,:));
errorbar(Ns(rge),fValLBs(rge),CILBs(rge),'o','markersize',1,'color',cm(4,:));
xlim([Ns(1),Ns(end)]);

figure();
load('WSchangeB');
plot(Bs,fValUBs,Bs,fValFKs,Bs,fValLKs,Bs,fValLBs);
legend('Knapsack Upper Bound','FK-Greedy','LK-Greedy','Knapsack Lower Bound','Location','southeast');
xlabel('Budget');
ylabel('Solution value');
title('PAP on WS networks, |V|=1000, 30 replications');
hold on; 
numBs = length(Bs);
rge = 1:interval:numBs;
CIUBs = varUBs*1.96/sqrt(numBs);
CIFKs = varFKs*1.96/sqrt(numBs);
CILKs = varLKs*1.96/sqrt(numBs);
CILBs = varLBs*1.96/sqrt(numBs);
errorbar(Bs(rge),fValUBs(rge),CIUBs(rge),'o','markersize',1,'color',cm(1,:));
errorbar(Bs(rge),fValFKs(rge),CIFKs(rge),'o','markersize',1,'color',cm(2,:));
errorbar(Bs(rge),fValLKs(rge),CILKs(rge),'o','markersize',1,'color',cm(3,:));
errorbar(Bs(rge),fValLBs(rge),CILBs(rge),'o','markersize',1,'color',cm(4,:));
xlim([Bs(1),Bs(end)]);

figure();
load('WSchangeN');
plot(Ns,fValUBs,Ns,fValFKs,Ns,fValLKs,Ns,fValLBs);
legend('Knapsack Upper Bound','FK-Greedy','LK-Greedy','Knapsack Lower Bound','Location','southeast');
xlabel('Number of Nodes');
ylabel('Solution value');
title('PAP on WS networks, B=3000, 30 replications');
hold on; 
numBs = length(Ns);
rge = 1:interval:numBs;
CIUBs = varUBs*1.96/sqrt(numNs);
CIFKs = varFKs*1.96/sqrt(numNs);
CILKs = varLKs*1.96/sqrt(numNs);
CILBs = varLBs*1.96/sqrt(numNs);
cm=lines(20);
errorbar(Ns(rge),fValUBs(rge),CIUBs(rge),'o','markersize',1,'color',cm(1,:));
errorbar(Ns(rge),fValFKs(rge),CIFKs(rge),'o','markersize',1,'color',cm(2,:));
errorbar(Ns(rge),fValLKs(rge),CILKs(rge),'o','markersize',1,'color',cm(3,:));
errorbar(Ns(rge),fValLBs(rge),CILBs(rge),'o','markersize',1,'color',cm(4,:));
xlim([Ns(1),Ns(end)]);

figure();
load('WSchangeWSB');
plot(WS_bs,fValUBs,WS_bs,fValFKs,WS_bs,fValLKs,WS_bs,fValLBs);
legend('Knapsack Upper Bound','FK-Greedy','LK-Greedy','Knapsack Lower Bound','Location','southeast');
xlabel('Probability of rewiring');
ylabel('Solution value');
title('PAP on WS networks, B=3000, 30 replications');
hold on; 
numBs = length(WS_bs);
rge = 1:interval:numBs;
CIUBs = varUBs*1.96/sqrt(numBs);
CIFKs = varFKs*1.96/sqrt(numBs);
CILKs = varLKs*1.96/sqrt(numBs);
CILBs = varLBs*1.96/sqrt(numBs);
cm=lines(20);
errorbar(WS_bs(rge),fValUBs(rge),CIUBs(rge),'o','markersize',1,'color',cm(1,:));
errorbar(WS_bs(rge),fValFKs(rge),CIFKs(rge),'o','markersize',1,'color',cm(2,:));
errorbar(WS_bs(rge),fValLKs(rge),CILKs(rge),'o','markersize',1,'color',cm(3,:));
errorbar(WS_bs(rge),fValLBs(rge),CILBs(rge),'o','markersize',1,'color',cm(4,:));
xlim([WS_bs(1),WS_bs(end)]);